### PR TITLE
Hide snp terms. Term id fixes

### LINKED ISSUE #1567: snplst/snplocus tabs show at filter ui
[test link](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22nav%22:{%22activeTab%22:3},%22termfilter%22:{%22filter%22:{%22type%22:%22tvslst%22,%22join%22:%22and%22,%22in%22:true,%22lst%22:[{%22type%22:%22tvs%22,%22tvs%22:{%22term%22:{%22id%22:%22diaggrp%22},%22values%22:[{%22key%22:%22Acute%20lymphoblastic%20leukemia%22}]}},{%22type%22:%22tvs%22,%22tvs%22:{%22term%22:{%22id%22:%22agedx%22},%22ranges%22:[{%22startunbounded%22:true,%22stop%22:10,%22stopinclusive%22:true}]}}]}}}). click AND, select option `+AND` and get below
it's on prod now. need to be suppressed
image

### PR DESCRIPTION
**Pull request by airenzp**
## Description

Closes #1567. Removes termid when calling violin.  Removes id validation not needed and causing issues for non dict terms.

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

File: server/src/validator.js [hunk 1]
```diff
@@ -57,7 +59,8 @@ export const byReqKey = {
 	},
 	term(value) {
 		const termWrapper = typeof value == 'string' ? JSON.parse(value) : value
-		if (!('id' in termWrapper)) throw 'missing termWrapper.id'
+		if (!('id' in termWrapper) && termWrapper.term?.type && isDictionaryType(termWrapper.term.type))
```
Comment (xzhou82) [inline server/src/validator.js:62]: just delete this check. it's based on legacy rule (requires tw.id but it's no more), enforces misleading name (term vs tw), too assumptive and doesn't cover other tw that could come from same request

**Review by xzhou82 — APPROVED** [review]

**Comment by xzhou82** [comment]
thanks a lot. next please enable geneExp in filter
