### PR TITLE
fix: handle missing childType when launching gene exp summary plot

### LINKED ISSUE #2387: gene exp summary chart won't load from dict ui

### PR DESCRIPTION
**Pull request by xzhou82**
## Description

closes #2387 
at http://localhost:3000/?noheader=1&massnative=hg38-test,TermdbTest, at dict ui, select `Gene exp` tab, search p53. violin loads

all ci pass; please address my questions

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

File: client/plots/summary.js [hunk 1]
```diff
@@ -407,11 +407,21 @@ export async function getPlotConfig(opts, app) {
 				} else if (config.term?.q?.mode == 'continuous' || config.term2?.q?.mode == 'continuous') {
 					/** Fix for summary tabs switching to different plots when opening and closing
```
Comment (xzhou82) [inline client/plots/summary.js:408]: please clarify purpose of this comment

File: client/plots/summary.js [hunk 2]
```diff
@@ -407,11 +407,21 @@ export async function getPlotConfig(opts, app) {
...
 					 * controls, changing settings, etc. */
+					config.childType = 'violin' // when mode=continuous is present, use violin by default and allow override below.
 					const state = app.getState()
-					if (state && state.plots) {
-						config.childType = state.plots.find(p => p.id === config.id).childType
-					} else config.childType = opts.childType || 'violin'
-				} else config.childType = 'barchart'
+					if (state?.plots) {
```
Comment (xzhou82) [inline client/plots/summary.js:412]: do you know in what condition will state be undefined?

File: client/plots/summary.js [hunk 3]
```diff
@@ -407,11 +407,21 @@ export async function getPlotConfig(opts, app) {
...
+						const p = state.plots.find(p => p.id === config.id)
+						if (p?.childType) {
+							config.childType = p.childType
+						} else {
+							// p.childType maybe missing (?), in such case do not change config.childType
```
Comment (xzhou82) [inline client/plots/summary.js:417]: and in what condition will p.childType be missing?

Comment (siosonel) [reply client/plots/summary.js]: I commented in my commit

File: client/plots/summary.js (hunk 2 above)
Comment (siosonel) [reply client/plots/summary.js]: should not even use `const state = app.getState()`, simply use the first argument since it's the same config.

File: client/plots/summary.js (hunk 1 above)
Comment (siosonel) [reply client/plots/summary.js]: This comment has been removed in my commit.

**Review by siosonel — APPROVED** [review]
