### PR TITLE
fix: improve roundValueAuto to allow to only return numbers for computing

### LINKED ISSUE #2434: numeric tvs edit ui breaks by forcing display of scientific notation values in INPUT
[test link](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22nav%22:{%22activeTab%22:3},%22termfilter%22:{%22filter%22:{%22type%22:%22tvslst%22,%22join%22:%22%22,%22in%22:true,%22lst%22:[{%22type%22:%22tvs%22,%22tvs%22:{%22term%22:{%22id%22:%22aaclassic_5%22,%22name%22:%22Cumulative%20Alkylating%20Agent%20(Cyclophosphamide%20Equivalent%20Dose)%22,%22type%22:%22float%22,%22values%22:{%22-8888%22:{%22label%22:%22Exposed%20but%20dose%20unknown%22,%22uncomputable%22:true},%22-9999%22:{%22label%22:%22Unknown%20treatment%20record%22,%22uncomputable%22:true}}},%22ranges%22:[{%22startunbounded%22:true,%22stop%22:10000,%22stopinclusive%22:true}]}}]}}}). click tvs and open edit ui, see scientific notation in INPUT. click Apply breaks

also, manually typing `x<12345` and click apply will only display 1e+4 and lost all precision. the fix should be not to use round value helper in INPUT

### PR DESCRIPTION
**Pull request by xzhou82**
## Description

closes #2434 
[test link](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22nav%22:%7B%22activeTab%22:3%7D,%22termfilter%22:%7B%22filter%22:%7B%22type%22:%22tvslst%22,%22join%22:%22%22,%22in%22:true,%22lst%22:%5B%7B%22type%22:%22tvs%22,%22tvs%22:%7B%22term%22:%7B%22id%22:%22aaclassic_5%22,%22name%22:%22Cumulative%20Alkylating%20Agent%20(Cyclophosphamide%20Equivalent%20Dose)%22,%22type%22:%22float%22,%22values%22:%7B%22-8888%22:%7B%22label%22:%22Exposed%20but%20dose%20unknown%22,%22uncomputable%22:true%7D,%22-9999%22:%7B%22label%22:%22Unknown%20treatment%20record%22,%22uncomputable%22:true%7D%7D%7D,%22ranges%22:%5B%7B%22startunbounded%22:true,%22stop%22:10000,%22stopinclusive%22:true%7D%5D%7D%7D%5D%7D%7D%7D), in tvs ui, INPUT box no longer shows scientific values e.g. 12345 rounds to 1.2e4 which is unreasonable and breaks ui (ui cannot parse scientific numbers)

all CI passed

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Review by karishma-gangwani — APPROVED** [review]
Thanks @xzhou82.  It works for me.

**Review by congyu-lu — COMMENTED** [review]
image
changing range to **_0 < x_**, still converted to scientific values

**Comment by xzhou82** [comment]
thanks Congyu for pointing out. the bigger issue is that by entering `x>0` it no longer sets stopUnbounded=true but will always sets a max value

**Comment by xzhou82** [comment]
@creilly8 updateTempRanges() logic is unclear

**Comment by creilly8** [comment]
The last four commits fix the problems with roundValueAuto without reverting the issue seen in the boxplot and violin plot (see https://github.com/stjude/proteinpaint/pull/2404). Also fixes the issue of when a user inputs a value outside the range, displaying a position rather than a value (see Congyu's example of entering 0<x when the available range is ~3-21). I added tests for clarity.

File: shared/utils/src/roundValue.js [hunk 1]
```diff
@@ -73,3 +74,17 @@ export function roundValue2(value) {
...
+/** Use to return displayed values in scientific notation
+ * Do not use for values intented for calculation later.
+ */
+export function formatValue(value, digits) {
+	const v = Number(value)
+	if (Number.isInteger(v)) return v
+	const abs = Math.abs(v)
+	if (abs < 1 || abs > 9999) {
+		//Number() reverts positive values less than 10^21 to a whole number
+		return abs > 9999 ? v.toPrecision(digits) : Number(v.toPrecision(digits))
```
Comment (xzhou82) [inline shared/utils/src/roundValue.js:87]: should be `Number(v.toPrecision(digits))` it doesn't make sense to return string or number in different cases

File: client/filter/tvs.density.js [hunk 2]
```diff
@@ -132,8 +144,19 @@ export function updateTempRanges(xscale, s, range, inputRange, minvalue, maxvalu
 	}
 }
 
+/** Set the start and stop displayed to the user
+ * Encapsulated and exported to verify usage via testing and CI.
+ */
+
+export function setStartStopDisplays(range, inputRange) {
```
Comment (xzhou82) [inline client/filter/tvs.density.js:151]: explain these two params

File: shared/utils/src/test/roundvalue.unit.spec.js [hunk 3]
```diff
@@ -13,47 +13,68 @@ tape('roundValue tests', function (test) {
...
-
-	value = 0.000056
-	rounded = 5.6e-5
-	test.equal(roundValueAuto(value), rounded, `should return ${rounded}`)
+	test.equal(roundValue2(value), rounded, `should return ${rounded}`)
 
 	value = 10549.23556789
 	rounded = '1.1e+4'
+	let r2 = 10549
+	test.equal(roundValueAuto(value, true), rounded, `should return ${rounded}`)
```
Comment (xzhou82) [inline shared/utils/src/test/roundvalue.unit.spec.js:26]: what does `roundValueAuto(value)` return? add test

File: shared/utils/src/test/roundvalue.unit.spec.js [hunk 4]
```diff
@@ -1,5 +1,5 @@
 import tape from 'tape'
-import { roundValueAuto } from '../roundValue.js'
+import { roundValueAuto, roundValue2 } from '../roundValue.js'
```
Comment (xzhou82) [inline shared/utils/src/test/roundvalue.unit.spec.js:2]: decimalPlacesUntilFirstNonZero is a key function. why is it not tested?

Comment (creilly8) [reply shared/utils/src/test/roundvalue.unit.spec.js:2]: Looks like it wasn't considered when this file was created.

File: shared/utils/src/test/roundvalue.unit.spec.js (hunk 3 above)
Comment (creilly8) [reply shared/utils/src/test/roundvalue.unit.spec.js]: In that instance it's probably best to use `roundValue` with the zero digits. There's nothing inherently wrong with these functions. Rather when to use them is, at least to me, opaque. It would be helpful to create a guideline of how numbers ought to be rendered. For instance scientific notation should be used for axis and scales, but not for user inputs and raw counts. Maybe even a blurb in roundValue.js would be sufficient.

File: client/filter/tvs.density.js (hunk 2 above)
Comment (creilly8) [reply client/filter/tvs.density.js:154]: I added comments in [6c25f4d](https://github.com/stjude/proteinpaint/pull/2439/commits/6c25f4d3a9ca5b584010b5d3a3aad0d0d2fe761b)

File: shared/utils/src/roundValue.js (hunk 1 above)
Comment (creilly8) [reply shared/utils/src/roundValue.js:88]: I added a comment in [6c25f4d](https://github.com/stjude/proteinpaint/pull/2439/commits/6c25f4d3a9ca5b584010b5d3a3aad0d0d2fe761b)

File: shared/utils/src/test/roundvalue.unit.spec.js [hunk 5]
```diff
@@ -13,47 +13,68 @@ tape('roundValue tests', function (test) {
...
+	rounded = 549.24
+	r2 = 549
 	test.equal(roundValueAuto(value), rounded, `should return ${rounded}`)
+	test.equal(roundValue2(value), r2, `should return ${r2}`)
 
 	value = -89378.345862
 	rounded = '-8.9e+4'
-	test.equal(roundValueAuto(value), rounded, `should return ${rounded}`)
+	r2 = -89378
+	test.equal(roundValueAuto(value, true), rounded, `should return ${rounded}`)
```
[the remark this answers is not in the document]
Comment (creilly8) [reply shared/utils/src/test/roundvalue.unit.spec.js]: The tests are updated in this commit: https://github.com/stjude/proteinpaint/pull/2439/commits/6e4da093b972ecc62f0ef1362eda8b0542eae0ab

File: shared/utils/src/test/roundvalue.unit.spec.js [hunk 6]
```diff
@@ -9,51 +15,121 @@ tape('\n', function (test) {
...
-tape('roundValue tests', function (test) {
-	let value = 1.23456789e-10
-	let rounded = 1.2e-10
-	test.equal(roundValueAuto(value), rounded, `should return ${rounded}`)
+tape('roundValueAuto()', function (test) {
+	let value, rounded, formatted
+
+	value = 1.23456789e-10
+	rounded = 1.2e-10
+	test.equal(roundValueAuto(value), rounded, `Should return rounded value=${rounded} for input value=${value}`)
```
Comment (xzhou82) [inline shared/utils/src/test/roundvalue.unit.spec.js:23]: there's anxiety whether `(value,true)` returns a different value. please add such tests

File: shared/utils/src/test/roundvalue.unit.spec.js [hunk 7]
```diff
@@ -9,51 +15,121 @@ tape('\n', function (test) {
...
+
+	value = 1000
+	test.equal(roundValueAuto(value), value, `Should return input value=${value} unchanged`)
+
+	value = 1000.1234
+	rounded = 1000.12
+	test.equal(roundValueAuto(value), rounded, `Should return rounded value=${rounded} for input value=${value}`)
+
+	value = -0.0001
+	test.equal(roundValueAuto(value), value, `Should return rounded value=${rounded} for input value=${value}`)
```
Comment (xzhou82) [inline shared/utils/src/test/roundvalue.unit.spec.js:68]: test msg typo, should be value but not `rounded`

File: shared/utils/src/roundValue.js [hunk 8]
```diff
@@ -11,19 +11,20 @@ digits: number of digits to round to
...
 	return Number(v.toFixed(digits))
 }
 
-export function roundValueAuto(value) {
+/** Rounds numbers to the appropriate decimal point
+ * if format is true, returns either a number or string in
+ * scientific notation.
+ */
+
+export function roundValueAuto(value, format = false) {
```
Comment (xzhou82) [inline shared/utils/src/roundValue.js:23]: roundValueAuto(value) will always add 2 decimals even for very large (absolute) numbers, which is not necessary. please note this as a TODO

File: shared/utils/src/test/roundvalue.unit.spec.js (hunk 4 above)
Comment (xzhou82) [reply shared/utils/src/test/roundvalue.unit.spec.js:2]: will leave it as good first issue

File: shared/utils/src/test/roundvalue.unit.spec.js (hunk 3 above)
Comment (xzhou82) [reply shared/utils/src/test/roundvalue.unit.spec.js]: this is the usecase that roundValueAuto() doesn't handle well (two decimals unnecessary), and it's not possible to use roundValue(x,0) since that violates generalization policy. still the issue of two decimals are minor and okay to merge

image

File: shared/utils/src/test/roundvalue.unit.spec.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (xzhou82) [reply shared/utils/src/test/roundvalue.unit.spec.js]: please evaluate if both `(x)` and `(x,true)` tests should be added for each case

File: shared/utils/src/test/roundvalue.unit.spec.js (hunk 6 above)
Comment (creilly8) [reply shared/utils/src/test/roundvalue.unit.spec.js:28]: The tests are added in https://github.com/stjude/proteinpaint/pull/2439/commits/9bb2c0ec26cef29c6a8c36b08018b55bf3246881

File: shared/utils/src/test/roundvalue.unit.spec.js (hunk 7 above)
Comment (creilly8) [reply shared/utils/src/test/roundvalue.unit.spec.js]: Fixed in https://github.com/stjude/proteinpaint/pull/2439/commits/9bb2c0ec26cef29c6a8c36b08018b55bf3246881

**Review by creilly8 — APPROVED** [review]
