### PR TITLE
table returns original row array index rather than sorted array to address GDC MAF UI bug

### LINKED ISSUE #2881: gdc maf: wrong data dowloaded
replicate errors Congyu found, by filtering for cases mutated for a gene http://localhost:3000/example.gdc.maf.html (please pull sjpp)

i think some are due to table.ts bug

### PR DESCRIPTION
**Pull request by xzhou82**
## Description

closes #2881 

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [ ] Tests: added and/or passed unit and integration tests, or N/A
- [ ] Todos: commented or documented, or N/A
- [ ] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

File: client/dom/table.ts [hunk 1]
```diff
@@ -679,17 +684,18 @@ function prepareBarPlot(cb: Barplot, i: number, rows: any) {
...
 	const ticksize = 4 // where is ticksize applied in axis?
 	const svg = th
 		.append('svg')
-		.attr('width', 2 * (cb?.xpadding ?? 0) + (cb?.axisWidth ?? 0))
+		.attr('width', 2 * (cb.xpadding || 0) + (cb.axisWidth || 0))
 		.attr('height', labfontsize + ypad + tickfontsize + ticksize + 1) // plus 1 so axis bottom line can fully show
-	if (!cb) return
-	const axis = axisTop(cb.scale).ticks(4)
+	const axis = axisTop(cb.scale).ticks(cb.tickCount || 4)
+	if (cb.tickFormat) axis.tickFormat(d3format(cb.tickFormat))
```
Comment (xzhou82) [inline client/dom/table.ts:697]: nice to apply SI notation but this causes tsc error

**Comment by xzhou82** [comment]
bug is at getCheckedRowIndex(). on resorting rows, this gives updated array index, causing a mismatch in gdc maf UI. 

please look into a fix to allow getCheckedRowIndex() to return *original* row index

File: client/dom/table.ts [hunk 2]
```diff
@@ -20,6 +22,7 @@ export type Cell = {
 	disabled?: boolean
 	/** may be used as a reference ID for aria-labelledby, or other use */
 	elemId?: string
+	id?: number
```
Comment (xzhou82) [inline client/dom/table.ts:25]: please comment on purpose

**Comment by xzhou82** [comment]
http://localhost:3000/?genome=hg38-test&gene=p53&mds3=TermdbTest breaks at Variant > List

**Comment by xzhou82** [comment]
samplescatter CI breaks

File: client/dom/table.ts [hunk 3]
```diff
@@ -174,6 +181,14 @@ export function renderTable({
 	validateInput()
 	let _selectedRowStyle = selectedRowStyle
 
+	/** Assign a persistent id that does not change on sort
+	 * Arg is mutable. Use structuredClone to avoid changing
+	 * the input rows */
+	let _rows = structuredClone(rows)
+	_rows.forEach((row, i) => {
+		row.push({ id: i })
```
Comment (xzhou82) [inline client/dom/table.ts:189]: bad to `row.push({id})`.
on table sort, maintain a mapping from new array index to old index, and return old index to callback. everything will continue to work

**Review by creilly8 — APPROVED** [review]

**Comment by xzhou82** [comment]
this bug fix should be merged to GDC release branch too
