### PR TITLE
gdc oncomatrix bug fix to add dictionary term from row group menu

### LINKED ISSUE #1057: in gdc oncomatrix, add dictionary term from row group menu breaks
[test link](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22GDC%22,%22genome%22:%22hg38%22,%22nav%22:{%22header_mode%22:%22hidden%22},%22plots%22:[{%22chartType%22:%22matrix%22,%22termgroups%22:[{%22lst%22:[{%22term%22:{%22name%22:%22MYC%22,%22type%22:%22geneVariant%22}},{%22term%22:{%22name%22:%22HOXA1%22,%22type%22:%22geneVariant%22}},{%22id%22:%22case.disease_type%22},{%22id%22:%22case.diagnoses.age_at_diagnosis%22}]}],%22divideBy%22:{%22id%22:%22case.demographic.gender%22}}]}). click `...` on the right of the only group and select `add rows`

image

add `Primary sites` breaks

categorical.ts:373 Uncaught (in promise) TypeError: Cannot add property groupsetting, object is not extensible

adding same term via `Variables` overhead button does not break. what's the difference?

please fix ASAP

### PR DESCRIPTION
**Pull request by congyu-lu**
## Description

fix #1057 

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Review by siosonel — APPROVED** [review]
works

File: client/plots/matrix.interactivity.js [hunk 1]
```diff
@@ -860,7 +860,8 @@ function setTermActions(self) {
 
 	async function submit_lst(termlst) {
 		const newterms = await Promise.all(
-			termlst.map(async term => {
+			termlst.map(async _term => {
+				const term = structuredClone(_term)
```
Comment (xzhou82) [inline client/plots/matrix.interactivity.js:864]: must comment on why it was breaking before
