### PR TITLE
SC fix for issue #2780

### LINKED ISSUE #2780: scrna: improvements
- [ ] plot size will auto change to 800: at `Plots` tab, check both UMAP and TSNE, then uncheck UMAP. the remaining TSNE plot becomes 800x800 rather than stay as default 600x600
- [ ] for gdc plot, at the sample table, move `Sample` column next to `Case` column

### PR DESCRIPTION
**Pull request by airenzp**
## Description

Closes #2780. Removed experimentColumns handling not used. Added sample info and gene or cluster if applicable in filename downloaded

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Review by compbiolover — DISMISSED** [review]
This works great. The only thing that might be a little confusing is now we have Sample and Sample right next to each other. Maybe they should be named Case and the other Sample? Just a thought
Screenshot 2025-02-11 at 11 11 12

File: client/plots/singleCellPlot.js [hunk 1]
```diff
@@ -1421,15 +1420,11 @@ class singleCellPlot {
...
-		// add in optional experiment columns
-		for (const c of s.experimentColumns || []) {
-			columns.push({ label: c.label, width: '20vw' })
-		}
-
 		// if samples are using experiments, add the hardcoded experiment column
 		if (samples.some(i => i.experiments)) {
 			// two hardcoded column names
-			columns.push({ label: 'Sample' }) // corresponds to this.samples[].experiments[].sampleName
+			columns.splice(1, 0, { label: 'Sample' }) //add after the case column
```
Comment (xzhou82) [inline client/plots/singleCellPlot.js:1426]: i wonder if `1` should be `SAMPLES_TAB`?

Comment (airenzp) [reply client/plots/singleCellPlot.js:1426]: 1 is the second column of the samples table

File: client/plots/singleCellPlot.js [hunk 2]
```diff
@@ -1377,6 +1378,7 @@ class singleCellPlot {
 		const rows = []
 		for (const sample of samples) {
 			if (sample.experiments)
+				//GDC
 				for (const exp of sample.experiments) {
 					// first cell is always sample name. sneak in experiment object to be accessed in click callback
 					const row = [{ value: sample.sample, __experimentID: exp.experimentID }]
```
Comment (xzhou82) [inline client/plots/singleCellPlot.js:1384]: i suppose just insert the sampleName element after this line rather than `.splice()` to same position later

File: client/plots/singleCellPlot.js [hunk 3]
```diff
@@ -857,7 +891,10 @@ class singleCellPlot {
 				inputs
 			})
 		}
-		this.components.controls.on('downloadClick.singleCellPlot', () => {
+		this.components.controls.on('downloadClick.singleCellPlot', async () => {
+			if (!this.state) return
+			const filename = await this.getSampleFilename(this.state)
```
Comment (xzhou82) [inline client/plots/singleCellPlot.js:896]: i don't think this computed file name is used for downloaded file

Comment (airenzp) [reply client/plots/singleCellPlot.js:896]: sorry I pushed this change by mistake

Comment (airenzp) [reply client/plots/singleCellPlot.js:898]: Now the logic to name the file downloaded is completed. Please check if ok

Comment (compbiolover) [reply client/plots/singleCellPlot.js:898]: @xzhou82  Checking now

Comment (compbiolover) [reply client/plots/singleCellPlot.js:898]: @xzhou82 @airenzp Just checked this with the latest commits and I now see the relevant sample/gene/cluster info for the sample I am downloading for both plot and legend

**Review by xzhou82 — APPROVED** [review]
