### PR TITLE
fix: scrna gene exp loader will throw to pass err to client; delete rds support

### LINKED ISSUE #2639: scrna gene exp data querying should report issues but not ignore them

### PR DESCRIPTION
**Pull request by xzhou82**
## Description

closes #2639 
to test with [this sjpp PR](https://github.com/stjude/sjpp/pull/632)

both gdc and native ds works
no tsc err in both repos

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [ ] Tests: added and/or passed unit and integration tests, or N/A
- [ ] Todos: commented or documented, or N/A
- [ ] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

File: shared/types/src/dataset.ts [hunk 1]
```diff
@@ -573,8 +573,6 @@ export type SingleCellGeneExpressionNative = {
 	storage_type: 'HDF5' | 'RDS'
 	/** dynamically added getter */
 	get?: (q: any) => any
-	/** cached gene exp bins */
-	sample2gene2expressionBins?: { [sample: string]: { [gene: string]: any } }
```
Comment (airenzp) [inline shared/types/src/dataset.ts:577]: there is a cache of geneExpression where we use this, in termdb.getDefaultBins
binsCache = ds.queries.singleCell.geneExpression.sample2gene2expressionBins[tw.term.sample]

Comment (xzhou82) [reply shared/types/src/dataset.ts]: thanks it's reverted

**Review by compbiolover — DISMISSED** [review]
