### PR TITLE
fix issue 1389

### LINKED ISSUE #1389: Do not use "not Not" or "not not" in association test labels
Open [diagrp overlay barchart](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22diaggrp%22},%22term2%22:{%22id%22:%22agedx%22}}],%22nav%22:{%22activeTab%22:1}})

Edit diagnosis group as follows:

image

Association tests shows `not Not Wilms`:

image

Should change logic in code to render `Wilms` instead of `not Not Wilms`

### PR DESCRIPTION
**Pull request by congyu-lu**
## Description

fix #1389 

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

File: client/plots/barchart.js [hunk 1]
```diff
@@ -921,6 +933,16 @@ function setRenderers(self) {
 			.style('font-weight', 'normal')
 			.html(noSkipped ? '' : 'N/A: association test skipped because of limited sample size <br>')
 	}
+
+	// a function used by generatePvalueTable to negate a term label
+	// TODO: add more conditions for better negation than "not termLable"
+	function negateTermLabel(termLabel) {
+		if (termLabel.toUpperCase().startsWith('NOT ')) {
```
Comment (xzhou82) [inline client/plots/barchart.js:940]: can merge now but should continue to evaluate this logic. e.g. can the name `not something` ever be one of 3 groups?

**Review by xzhou82 — APPROVED** [review]
