### PR TITLE
reuse getData in termdb.regression.js

### LINKED ISSUE #1626: support continuous non dict terms in regression as covariates

### PR DESCRIPTION
**Pull request by xzhou82**
## Description

closes #1626 

reusing getData() in termdb.regression.js addressed a longtime issue of redundant and unmaintainable code (for now they are commented off, can delete in later branches when fully tested)

all regression CI passed. if u have broken test:
1. lack of "regressionResultMsgs" feature flag
2. didn't install X11 (spline image render crash)

[all-pharm with gene exp works](http://localhost:3000/?noheader=1&mass={%22genome%22:%22hg38%22,%22dslabel%22:%22ALL-pharmacotyping%22,%22nav%22:{%22activeTab%22:1},%22plots%22:[{%22chartType%22:%22regression%22,%22regressionType%22:%22linear%22,%22outcome%22:{%22id%22:%22Asparaginase_normalizedLC50%22},%22independent%22:[{%22id%22:%22Age%22,%22q%22:{%22mode%22:%22continuous%22}},{%22id%22:%22Molecular%20subtype%22},{%22term%22:{%22type%22:%22geneExpression%22,%22gene%22:%22ASNS%22}}]}]})

can replicate [SF36~amputation](https://proteinpaint.stjude.org/survivorship/paper2024/figures/sf36-regression.html) with recently built sjlife db (not latest)

can replicate the [simple mbmeta one](https://proteinpaint.stjude.org/?mass-session-file=files/hg38/mbmeta/figure-sessions/figure-2/figure_2_regression.txt), the complex one should be manually tested

things not working and will be fixed in new branch:
1. adding multiple gene exp terms breaks client
2. adding expression and mutation of same gene likely to break client; solution is to change client to track terms by tw.$id
4. interaction term relationship should be recorded by tw.$id but not tw.term.id
5. spline (needs testing by someone with X11)
6. snplst and snplocus, should test with latest sjlife db

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by xzhou82** [comment]
@karishma-gangwani you can use this branch to test gene exp in ALL-pharm to see if results are valid. there are additional issues to be addressed but may not affect ALL-pharm

File: server/src/termdb.regression.js [hunk 1]
```diff
@@ -1073,47 +1073,90 @@ function getLine4OneSnp(snpid, tw) {
...
+		const obj = {
+			sample: sid,
+			id2value: new Map()
+		} // annotation obj for this sample
+
+		for (const tw of terms) {
+			// somehow, outcome term is identified by $id, input terms lacks $id!!! may fix on client to assign $id to input terms?
+			if (tw.$id in result.samples[sidString]) {
+				// FIXME change to always using t.$id
+				obj.id2value.set(tw.term.id || tw.$id, result.samples[sidString][tw.$id])
```
Comment (xzhou82) [inline server/src/termdb.regression.js:1121]: TODO change to reuse tw.$id to track sample data. downstream code still uses tw.term.id which will not support non-dict terms

**Comment by karishma-gangwani** [comment]
for Dasatinib LC50 normalized: add cdk6 first and cdk2 second breaks.

```
TypeError: Cannot read properties of undefined (reading 'length')
    at InputTerm.renderInteractionPrompt (regression.inputs.term.js:432:36)
    at InputTerm.main (regression.inputs.term.js:167:9)
    at async Promise.all (:3000/index 2)
    at async RegressionInputs.main (regression.inputs.js:124:4)
    at async Regression.main (regression.js:78:4)
    at async Object.update (index.js:490:8)
    at async Promise.all (:3000/index 1)
    at async Object.update (index.js:499:4)
    at async Promise.all (:3000/index 1)
    at async Object.dispatch (index.js:347:5) 
```

**Comment by xzhou82** [comment]
thanks. client breaks when two gene exp terms are present. likely due to not using tw.$id

**Comment by karishma-gangwani** [comment]
> thanks. client breaks when two gene exp terms are present. likely due to not tracking with tw.$id

I am still seeing the same error @xzhou82

**Comment by karishma-gangwani** [comment]
for logistic regression when univariate is also enabled, a gene term shows 'continuous' under category although its not really a category but the modality of the data. can we remove this and leave it blank? 

image

Logistic regression works for me.

**Comment by xzhou82** [comment]
i want to fix the regression client code issue in next branch. please see PR TODOs

i don't know how to repeat your other issue. if minor, i suggest to fix it later and you can create issue with description
i also found issue with the `Univariate` checkbox. it should be refactored and not using the `isneuroonc` flag

**Comment by karishma-gangwani** [comment]
> i want to fix the regression client code issue in next branch. please see PR TODOs
> 
> i don't know how to repeat your other issue. if minor, i suggest to fix it later and you can create issue with description i also found issue with the `Univariate` checkbox. it should be refactored and not using the `isneuroonc` flag

okay that's fine. Thanks, I will approve.

**Review by karishma-gangwani — APPROVED** [review]

**Comment by karishma-gangwani** [comment]
can we disable linear and logistic regression on mbmeta? There are things breaking there.

**Comment by xzhou82** [comment]
doesn't look it breaks but good idea. i created a new issue
